 ￼
language: python

addons:
  apt:
    packages:
      - libhdf5-serial-dev

python:
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
# command to install dependencies
install:
  - pip install .

# command to run tests
script:
  - pytest

deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: "Your encrypted password"
